In [10]:
# Consider the below code to answer further questions:

# import numpy as np
# list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
# array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
# to print the data types of both the variables.

# Q2. Write a code to print the data type of each and every element of both the variables list_ and 
# arra_list.

# Q3. Considering the following changes in the variable, array_list:

# array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and 
# arra_list? If so then print the data types of each and every element present in both the variables, list_ 
# and arra_list.

# Consider the below code to answer further questions:

# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
# num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:

# (i)	 shape

# (ii) size


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
# creation function.

# [Hint: The size of the array will be 9 and the shape will be (3,3).]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [3]:
# Consider the below code to answer further questions:

import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
# to print the data types of both the variables.

In [5]:
# Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ is a Python list, while array_list is a NumPy array.
# To print the data types of both variables, you can use the type() function as follows:

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and 
# arra_list.

In [7]:
# For list_
for element in list_:
    print(type(element))

# For array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and 
# arra_list? If so then print the data types of each and every element present in both the variables, list_ 
# and arra_list.

In [9]:
# Yes, there will be a difference in the data type of the elements present in both list_ and array_list. 
# When you create array_list with the dtype parameter set to int, the string elements in list_ will be converted to integer data type.

# For list_
for element in list_:
    print(type(element))

# For array_list with dtype=int
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [11]:
# Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [12]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i)	 shape
# (ii) size

In [13]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:

# Finding shape of the array
print("Shape of the array: ", num_array.shape)

# Finding size of the array
print("Size of the array: ", num_array.size)


Shape of the array:  (2, 3)
Size of the array:  6


In [17]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
# creation function.

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [21]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])